<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php'; require_admin();
$id=(int)($_GET['id']??0);$post=['menu_item_id'=>'','title'=>'','body'=>'','price_text'=>'','image_path'=>'','call_to_action'=>'Se menuen','published_at'=>date('Y-m-d\TH:i'),'is_active'=>1,'sort_order'=>0];
if($id){$s=db()->prepare('SELECT * FROM food_posts WHERE id=?');$s->execute([$id]);$post=$s->fetch();$post['published_at']=date('Y-m-d\TH:i',strtotime($post['published_at']));}
$items=db()->query('SELECT id,title FROM menu_items ORDER BY title')->fetchAll();$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$image=$post['image_path']?:null;$u=store_uploaded_image($_FILES['image']??[],'posts');if($u)$image=$u;$data=[($_POST['menu_item_id']??'')!==''?(int)$_POST['menu_item_id']:null,trim($_POST['title']),trim($_POST['body']),trim($_POST['price_text']),$image,trim($_POST['call_to_action']),date('Y-m-d H:i:s',strtotime($_POST['published_at'])),isset($_POST['is_active'])?1:0,(int)$_POST['sort_order']];if($data[1]===''||$data[2]==='')throw new RuntimeException('Titel og tekst skal udfyldes.');if($id){$sql='UPDATE food_posts SET menu_item_id=?,title=?,body=?,price_text=?,image_path=?,call_to_action=?,published_at=?,is_active=?,sort_order=? WHERE id=?';$data[]=$id;}else{$sql='INSERT INTO food_posts(menu_item_id,title,body,price_text,image_path,call_to_action,published_at,is_active,sort_order) VALUES(?,?,?,?,?,?,?,?,?)';}db()->prepare($sql)->execute($data);flash('success','Billedet/opslaget er gemt og kan vises på hjemmesiden.');redirect('/admin/posts.php');}catch(Throwable $e){$error=$e->getMessage();$post=array_merge($post,$_POST);}}
admin_layout_start($id?'Ret billede':'Tilføj billede','posts');
?>
<?php if($error): ?><div class="alert alert--error"><?= h($error) ?></div><?php endif; ?>
<div class="page-intro"><p class="admin-kicker">Madgalleri</p><h2><?= $id ? 'Her kan du rette billedet' : 'Her kan du tilføje et nyt billede' ?></h2><p>Upload et madbillede, skriv en kort titel og en kort tekst. Hvis feltet “Vis på hjemmesiden” er markeret, kan billedet blive vist i madgalleriet.</p></div>
<form method="post" enctype="multipart/form-data" class="form-card"><?= csrf_field() ?><div class="form-grid"><div class="field"><label>Titel *</label><input name="title" value="<?= h($post['title']) ?>" required placeholder="F.eks. Dagens ret"></div><div class="field"><label>Knyt til ret</label><select name="menu_item_id"><option value="">Ingen bestemt ret</option><?php foreach($items as $it): ?><option value="<?= (int)$it['id'] ?>" <?= (int)$post['menu_item_id']===(int)$it['id']?'selected':'' ?>><?= h($it['title']) ?></option><?php endforeach; ?></select><small>Valgfrit. Bruges kun hvis billedet hører til en bestemt ret.</small></div><div class="field field--full"><label>Kort tekst *</label><textarea name="body" required placeholder="Skriv en kort appetitlig tekst"><?= h($post['body']) ?></textarea></div><div class="field"><label>Pristekst</label><input name="price_text" value="<?= h($post['price_text']) ?>" placeholder="65 kr. · XL 80 kr."><small>Kan stå tomt.</small></div><div class="field"><label>Sortering</label><input type="number" name="sort_order" value="<?= h($post['sort_order']) ?>"><small>Lavere tal vises først.</small></div><div class="field field--full"><label>Billede</label><?php if($post['image_path']): ?><img class="image-preview" data-image-preview src="<?= h(base_url($post['image_path'])) ?>" alt=""><?php else: ?><img class="image-preview" data-image-preview alt=""><?php endif; ?><input data-image-input type="file" name="image" accept="image/jpeg,image/png,image/webp"><small>Vælg et billede fra mobil eller computer.</small></div><input type="hidden" name="call_to_action" value="Se menuen"><input type="hidden" name="published_at" value="<?= h($post['published_at']) ?>"><div class="field field--full"><label class="check"><input type="checkbox" name="is_active" <?= $post['is_active']?'checked':'' ?>> Vis på hjemmesiden</label></div></div><div class="form-actions sticky-save"><a class="button button--soft" href="<?= h(base_url('/admin/posts.php')) ?>">Annuller</a><button class="button button--primary"><i class="fa-solid fa-floppy-disk"></i> Gem billede</button></div></form>
<?php admin_layout_end(); ?>
