<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require_admin();

$keys = [
    'site_name','phone','email','address','opening_hours','opening_hours_highlight','facebook_url','marquee_text',
    'hero_kicker','hero_title','hero_intro','hero_fact_1_number','hero_fact_1_text','hero_fact_2_number','hero_fact_2_text','hero_fact_3_number','hero_fact_3_text','hero_card_text',
    'gallery_heading','gallery_intro','menu_heading','menu_intro_text','contact_heading','contact_intro','footer_text'
];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    foreach ($keys as $k) set_setting($k, trim((string)($_POST[$k] ?? '')));
    flash('success', 'Tekst og info er gemt. Åbn hjemmesiden for at se ændringerne.');
    redirect('/admin/settings.php');
}
$defaultMarquee = "Mad er vores produkt – glæde er vores brand ❤️\nDagens ret tir–tor\nTakeaway afhentes kl. 17–19\nGlæder os til at se jer";
admin_layout_start('Tekst & info', 'settings');
?>
<form method="post" class="form-card form-card--wide"><?= csrf_field() ?>
  <div class="page-intro page-intro--inside"><p class="admin-kicker">Hej Eva</p><h2>Her kan du rette tekst, info og åbningstider</h2><p>Her kan du ændre de tekster og oplysninger, der vises på hjemmesiden. Skriv dine ændringer og tryk Gem nederst på siden.</p></div>

  <div class="settings-block"><h3><i class="fa-solid fa-forward"></i> Teksten der kører øverst</h3><p>Her kan du ændre teksten, der kører øverst hen over skærmen på hjemmesiden. Skriv gerne én besked pr. linje.</p><div class="field field--full"><label>Løbende tekst øverst på hjemmesiden</label><textarea name="marquee_text" rows="5" placeholder="Skriv én tekst pr. linje"><?= h(setting('marquee_text', $defaultMarquee)) ?></textarea><small>Hver linje bliver vist som en del af den løbende tekst.</small></div></div>

  <div class="settings-block"><h3><i class="fa-solid fa-house"></i> Forsiden</h3><p>Her kan du ændre de vigtigste tekster øverst på hjemmesiden.</p><div class="form-grid"><div class="field"><label>Lille tekst over overskriften</label><input name="hero_kicker" value="<?= h(setting('hero_kicker','Sportscafé · Lystrup Idrætscenter')) ?>"></div><div class="field"><label>Kort tekst i billedkortet</label><input name="hero_card_text" value="<?= h(setting('hero_card_text','Mad er vores produkt – glæde er vores brand ❤️')) ?>"></div><div class="field field--full"><label>Stor overskrift</label><textarea name="hero_title" rows="3"><?= h(setting('hero_title', "Mad der\nsamler\nmennesker.")) ?></textarea><small>Skriv gerne linjeskift, hvis overskriften skal stå på flere linjer.</small></div><div class="field field--full"><label>Tekst under overskriften</label><textarea name="hero_intro" rows="4"><?= h(setting('hero_intro','Mad er vores produkt – men glæde er vores brand ❤️ Hjemmelavede retter, varmt værtsskab og et sted hvor sportsfolk, familier og venner altid føler sig velkomne.')) ?></textarea></div><div class="field"><label>Faktaboks 1 - tal</label><input name="hero_fact_1_number" value="<?= h(setting('hero_fact_1_number','3')) ?>"></div><div class="field"><label>Faktaboks 1 - tekst</label><input name="hero_fact_1_text" value="<?= h(setting('hero_fact_1_text','dage med dagens ret')) ?>"></div><div class="field"><label>Faktaboks 2 - tal</label><input name="hero_fact_2_number" value="<?= h(setting('hero_fact_2_number','65 kr')) ?>"></div><div class="field"><label>Faktaboks 2 - tekst</label><input name="hero_fact_2_text" value="<?= h(setting('hero_fact_2_text','hjemmelavet mad')) ?>"></div><div class="field"><label>Faktaboks 3 - tal</label><input name="hero_fact_3_number" value="<?= h(setting('hero_fact_3_number','17–19')) ?>"></div><div class="field"><label>Faktaboks 3 - tekst</label><input name="hero_fact_3_text" value="<?= h(setting('hero_fact_3_text','takeaway efter aftale')) ?>"></div></div></div>

  <div class="settings-block"><h3><i class="fa-solid fa-images"></i> Galleri og menu</h3><p>Her kan du rette overskrifterne over madgalleriet og menukortet.</p><div class="form-grid"><div class="field"><label>Galleri overskrift</label><input name="gallery_heading" value="<?= h(setting('gallery_heading','Smag med øjnene')) ?>"></div><div class="field"><label>Galleri undertekst</label><input name="gallery_intro" value="<?= h(setting('gallery_intro','Hjemmelavet mad fra Café LIF — fotos fra vores køkken.')) ?>"></div><div class="field field--full"><label>Menu overskrift</label><textarea name="menu_heading" rows="2"><?= h(setting('menu_heading', "Se menuen.\nKontakt os for bestilling.")) ?></textarea></div><div class="field field--full"><label>Menu undertekst</label><textarea name="menu_intro_text" rows="3"><?= h(setting('menu_intro_text','Her kan du se retter, priser og muligheder. Ring eller skriv, hvis du vil bestille eller høre mere.')) ?></textarea></div></div></div>

  <div class="settings-block"><h3><i class="fa-solid fa-clock"></i> Kontakt og åbningstider</h3><p>Her kan du rette telefon, e-mail, adresse og åbningstider.</p><div class="form-grid"><div class="field"><label>Caféens navn</label><input name="site_name" value="<?= h(setting('site_name','Café LIF')) ?>"></div><div class="field"><label>Telefon</label><input name="phone" value="<?= h(setting('phone')) ?>"></div><div class="field"><label>E-mail</label><input type="email" name="email" value="<?= h(setting('email')) ?>"></div><div class="field"><label>Facebook-link</label><input name="facebook_url" value="<?= h(setting('facebook_url')) ?>"></div><div class="field field--full"><label>Adresse</label><input name="address" value="<?= h(setting('address')) ?>"></div><div class="field field--full"><label>Åbningstider</label><textarea name="opening_hours" rows="4"><?= h(setting('opening_hours')) ?></textarea><small>Skriv fx én linje pr. åbningstid eller besked.</small></div><div class="field field--full"><label>Ekstra tekst under åbningstider</label><input name="opening_hours_highlight" value="<?= h(setting('opening_hours_highlight','Dagens ret: Tirsdag, onsdag & torsdag · takeaway kl. 17–19')) ?>"></div><div class="field field--full"><label>Kontakt-overskrift</label><textarea name="contact_heading" rows="2"><?= h(setting('contact_heading', "Glæder os til\nat se jer")) ?></textarea></div><div class="field field--full"><label>Kontakt-tekst</label><textarea name="contact_intro" rows="3"><?= h(setting('contact_intro','Har du spørgsmål om dagens ret, tapas, mad ud af huset eller selskaber, så kontakt os direkte. Så får du hurtigt svar.')) ?></textarea></div><div class="field field--full"><label>Tekst nederst på hjemmesiden</label><textarea name="footer_text" rows="3"><?= h(setting('footer_text','Mad er vores produkt – men glæde er vores brand ❤️ Et hyggeligt samlingspunkt i Lystrup Idrætscenter.')) ?></textarea></div></div></div>

  <div class="form-actions sticky-save"><button class="button button--primary"><i class="fa-solid fa-floppy-disk"></i> Gem tekst og info</button></div>
</form>
<?php admin_layout_end(); ?>
