-- Run manually on Test before copying the updated order endpoint.
-- MySQL/MariaDB INFORMATION_SCHEMA guard; repeatable without dropping data.
SET @ddl := (SELECT IF(COUNT(*)=0, 'ALTER TABLE orders ADD COLUMN confirmation_email_requested TINYINT(1) NOT NULL DEFAULT 0', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='orders' AND COLUMN_NAME='confirmation_email_requested');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @ddl := (SELECT IF(COUNT(*)=0, 'ALTER TABLE orders ADD COLUMN customer_mail_sent_at DATETIME NULL', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='orders' AND COLUMN_NAME='customer_mail_sent_at');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @ddl := (SELECT IF(COUNT(*)=0, 'ALTER TABLE orders ADD COLUMN customer_mail_error TEXT NULL', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='orders' AND COLUMN_NAME='customer_mail_error');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @ddl := (SELECT IF(COUNT(*)=0, 'ALTER TABLE orders ADD COLUMN admin_mail_sent_at DATETIME NULL', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='orders' AND COLUMN_NAME='admin_mail_sent_at');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @ddl := (SELECT IF(COUNT(*)=0, 'ALTER TABLE orders ADD COLUMN admin_mail_error TEXT NULL', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='orders' AND COLUMN_NAME='admin_mail_error');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
